from abc import ABC, abstractmethod


class LLMProvider(ABC):
    """
    Abstract base class for LLM providers.
    Decouples application logic from specific model vendors.
    """

    @abstractmethod
    def generate(self, prompt: str) -> str:
        """
        Sends a prompt to the LLM and returns the generated text response.

        Args:
            prompt (str): The prompt string to be sent to the model.

        Returns:
            str: The text content generated by the model.
        """
        pass
